# Generated by Django 4.1.2 on 2022-10-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advocate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("profile_pic", models.ImageField(blank=True, null=True, upload_to="")),
                ("short_bio", models.TextField(blank=True, max_length=255, null=True)),
                ("long_bio", models.TextField(blank=True, null=True)),
                ("advocate_years_exp", models.PositiveIntegerField(default=1)),
                ("links", models.JSONField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="advocates",
            field=models.ManyToManyField(
                blank=True, related_name="companys", to="core.advocate"
            ),
        ),
    ]
